name: Release Pipeline For Registered Model (No Code Deploy) - $(Build.DefinitionName) - $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../../recipes/common/Variables.yml

stages:

  - stage: DeployToTest
    displayName: Deploy model to Test (Azure Container Instance)
    jobs:
      - template: ../../recipes/cd/Deploy.yml
        parameters:
          rm-service-connection: ${{ variables['RM_SERVICE_CONNECTION'] }}
          name: ${{ variables['RISK_MODEL_ACI_SERVICE_NAME'] }}
          workspace-name: ${{ variables['WORKSPACE'] }}
          resource-group: ${{ variables['RESOURCE_GROUP'] }}
          model: ${{ variables['RISK_MODEL_NAME'] }}:1
          compute-type: aci

  - stage: DeployToProd
    displayName: Deploy to Prod (AKS)
    jobs:
      # Perform an empty deploy job for approval (This is the way in Azure Devops)
      - deployment: Approval
        displayName: Approval for rolling out to production
        environment: 'Prod'

      - template: ../../recipes/cd/Deploy.yml
        parameters:
          rm-service-connection: ${{ variables['RM_SERVICE_CONNECTION'] }}
          name: ${{ variables['RISK_MODEL_AKS_SERVICE_NAME'] }}
          workspace-name: ${{ variables['WORKSPACE'] }}
          resource-group: ${{ variables['RESOURCE_GROUP'] }}
          model: ${{ variables['RISK_MODEL_NAME'] }}:1
          compute-type: aks
