name: Img Batch Inference Pipeline - $(Build.DefinitionName) - $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../../recipes/common/Variables.yml
  - group: MLOPSVG

stages:
  - stage: PublishAndRunBatchInference
    displayName: Publish and run the batch inference pipeline
    jobs:
      - template: ../../recipes/ci/PublishBatchInferencePipeline.yml
        parameters:
          rm-service-connection: ${{ variables['RM_SERVICE_CONNECTION'] }}
          workspace-name:  ${{ variables['WORKSPACE'] }}
          resource-group:  ${{ variables['RESOURCE_GROUP'] }}
          aml_pipeline_yml_path: models/img-model/batch_score/pipeline/AMLBatchPipeline.yml
          aml_pipeline_name: img-img-pipeline
          run_pipeline: true
          run_experiment_name: img-batch-exp