name: Register Pretrained Img Model - $(Build.DefinitionName) - $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../../recipes/common/Variables.yml

stages:

  - stage: RegisterPretrainedImgkModel
    displayName: Register pretrained img model
    jobs:
      - template: ../../recipes/ci/RegisterModel.yml
        parameters:
          rm-service-connection: ${{ variables['RM_SERVICE_CONNECTION'] }}
          workspace-name: ${{ variables['WORKSPACE'] }}
          resource-group: ${{ variables['RESOURCE_GROUP'] }}
          name: ${{ variables['IMG_MODEL_NAME'] }}
          model-framework: 'TensorFlow'
          model-framework-version: '2.0.0'
          model-path: 'models/img-model/model/'