parameters:
  rm_service_connection: ''
  workspace: ''
  resource_group: ''
  model_name: ''
  aks_cluster: ''
  inference_config: models/${{ parameters.model_name }}/score/InferenceConfig.yml
  deployment_config: models/${{ parameters.model_name }}/score/deploymentConfig.yml
  model_metadata_artifact: 'model-metadata'

jobs:
  - job: DeployProdJob
    steps:
      - task: AzureCLI@1
        displayName: 'Install the CLI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - download: current
        displayName: Download artifact model metadata
        artifact: ${{ parameters.model_metadata_artifact }}

      - task: AzureCLI@1
        displayName: 'Deploy the model to AKS'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az ml model deploy -n ${{ parameters.model_name }}-svc-aks --ct ${{ parameters.aks_cluster }} -f $(Pipeline.Workspace)/model-metadata/model.json --ic ${{ parameters.inference_config }} --dc  ${{ parameters.deployment_config }} --overwrite --workspace-name ${{ parameters.workspace }} --resource-group ${{ parameters.resource_group }}'