parameters:
  rm_service_connection: ''
  workspace: ''
  resource_group: ''
  model_name: ''
  aks_cluster: ''
  inference_config: ''
  deployment_config: ''
  model_metadata_artifact: 'model-metadata'

jobs:
  - job: DeployProdJob

    variables:
      default_inference_config: models/${{ parameters.model_name }}/score/InferenceConfig.yml
      inference_config_var: ${{ coalesce(parameters.conda_dependencies_file ,  variables.default_conda_dependencies_file) }}
      # source directory
      default_deployment_config: models/${{ parameters.model_name }}/score/deploymentConfig.yml
      deployment_config_var: ${{ coalesce(parameters.source_directory ,  variables.default_source_directory) }}

    steps:
      - task: AzureCLI@1
        displayName: 'Install the CLI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - download: current
        displayName: Download artifact model metadata
        artifact: ${{ parameters.model_metadata_artifact }}

      - task: AzureCLI@1
        displayName: 'Deploy the model to AKS'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az ml model deploy -n ${{ parameters.model_name }}-svc-aks --ct ${{ parameters.aks_cluster }} -f $(Pipeline.Workspace)/model-metadata/model.json --ic  ${{ variables.inference_config_var }} --dc  ${{ variables.deployment_config_var }} --overwrite --workspace-name ${{ parameters.workspace }} --resource-group ${{ parameters.resource_group }}'