parameters:
  rm_service_connection: ''
  service_name: ''
  workspace: ''
  resource_group: ''
  model_id: ''
  inference_config: ''
  deployment_config: ''

jobs:
  - job: DeployToACI
    steps:
      - task: AzureCLI@1
        displayName: 'Install the CLI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - task: AzureCLI@1
        displayName: 'Deploy the model to ACI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az ml model deploy -n ${{ parameters.service_name }} -m ${{ parameters.model_id }} --ic  ${{ variables.inference_config_var }} --dc  ${{ variables.deployment_config_var }} --overwrite --workspace-name ${{ parameters.workspace }} --resource-group ${{ parameters.resource_group }}'