name: project_environment
dependencies:
  - python=3.6.2
  - pip==19.3.1
  - pip:
    - azureml-defaults==1.0.83
    - python-dotenv
    - azureml-dataprep[fuse,pandas]>=1.1.19
    - azureml-contrib-pipeline-steps
    - inference-schema[numpy-support]
    - numpy
    - pandas
    - pillow
    - tensorflow-gpu==2.0.0

channels:
- conda-forge