parameters:
  rm_service_connection: ''
  resource_group: ''
  workspace: ''
  aml_compute_sku: ''
  aml_compute_cluster: ''
  max_nodes: '3'

jobs:
      - job: CreateAMLComputeCluster
        steps:
          - task: AzureCLI@2
            displayName: 'Install the CLI'
            inputs:
              scriptType: bash
              azureSubscription:  ${{ parameters.rm_service_connection }}
              scriptLocation: inlineScript
              inlineScript: 'az extension add -n azure-cli-ml'

          - task: AzureCLI@2
            displayName: 'Provision compute cluster for training'
            inputs:
              scriptType: bash
              azureSubscription:  ${{ parameters.rm_service_connection }}
              scriptLocation: inlineScript
              inlineScript: 'az ml computetarget create amlcompute --max-nodes ${{ parameters.max_nodes }} --name ${{ parameters.aml_compute_cluster }} --vm-size ${{ parameters.aml_compute_sku }} --resource-group ${{ parameters.resource_group }} --vm-priority dedicated --workspace-name ${{ parameters.workspace }} --remote-login-port-public-access disabled'