trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../recipes/common/Variables.yml

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '${{ variables.RM_SERVICE_CONNECTION }}'
    action: 'DeleteRG'
    resourceGroupName: '${{ variables.RESOURCE_GROUP }}'
    location: '${{ variables.LOCATION }}'
  displayName: 'Tear down the environment'