#NOTE: This is a stopgap fix until CLI support is released for batch inference. For python program to look up workspace
#we need to define the following variables in Azure Devops under MLOPSVG Variable group:
#SUBSCRIPTION_ID, TENANT_ID, SP_APP_ID, SP_APP_SECRET

parameters:
  rm_service_connection: ''
  workspace: ''
  resource_group: ''
  aml_pipeline_yml_path: ''
  aml_pipeline_name: ''

jobs:
  - job: BatchInferencePipelinePublish
    steps:
    - task: AzureCLI@1
      displayName: 'Install the CLI'
      inputs:
        azureSubscription: ${{ parameters.rm_service_connection }}
        scriptLocation: inlineScript
        inlineScript: 'az extension add -n azure-cli-ml'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'

    - script: pip install azureml-sdk azureml-contrib-pipeline-steps python-dotenv
      displayName: 'Install libraries'

#    - bash: 'python -m models.utils.batch_inference.publish_batch_inf_pipeline --AML_PIPELINE_YML_PATH ${{ parameters.aml_pipeline_yml_path }} --AML_PIPELINE_NAME ${{ parameters.aml_pipeline_name }}'
#      workingDirectory: $(Build.SourcesDirectory)
#      displayName: 'Publish Batch Inference Pipeline'
    - task: PythonScript@0
      inputs:
        scriptSource: inline
        script: print("##vso[task.setvariable variable=PIPELINE_ID]","87744497-04b1-4d6c-ad8e-519e84a4ca1c")

    - bash: python -m models.utils.batch_inference.run_batch_inf_pipeline --PIPELINE_ID $(PIPELINE_ID)
      workingDirectory: $(Build.SourcesDirectory)
      displayName: 'Run Batch Inference Pipeline'
