parameters:
  service_name: ''
  postman_collection_file: ''

jobs:
  - job: RunNewmanTests

    variables:
      newman_test_dir: '$(System.DefaultWorkingDirectory)/newman_tests'
    steps:
      - bash: 'python -m models.utils.test.get_service_details --SERVICE_NAME ${{ parameters.service_name }}'
        displayName: "Look up scoring uri & api key"
        workingDirectory: $(Build.SourcesDirectory)

      - task: ShellScript@2
        displayName: install newman
        inputs:
          scriptPath: models/utils/test/install_newman.sh
          cwd: $(Build.SourcesDirectory)

      - bash: |
          mkdir $(newman_test_dir)
          newman run ${{ parameters.postman_collection_file }}  --global-var host="$(TMP_SCORING_URI)" --global-var api_key="$(TMP_API_KEY)" -r cli,junit --reporter-junit-export  $(newman_test_dir)
        displayName: "Run tests"
        workingDirectory: $(Build.SourcesDirectory)

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '*.xml'
          searchFolder:  $(newman_test_dir)
