parameters:
  rm_service_connection: ''
  workspace: ''
  resource_group: ''
  model_name: ''
  aml_compute_cluster: ''
  dataset_name: ''
  conda_dependencies_file: ''
  source_directory: ''
  entry_script: 'train.py'
  run_metadata_artifact: 'run-metadata'

jobs:
  - job: TrainJob
    displayName: Test Train

    steps:
      - publish: $(System.DefaultWorkingDirectory)/run.json
        displayName: Publish run metadata artifact
        artifact: ${{ parameters.run_metadata_artifact }}